### ISSUE TITLE
The link of PH2 dataset is not available

### ISSUE THREAD

**Issue by JingyeChen** [learningtitans/data-depth-design#1]
Thanks for your beautiful work! I want to download the PH2 dataset but unfortunately found the link https://www.dropbox.com/s/k88qukc20ljnbuo/PH2Dataset.rar was not availabe any more. So could you please send this dataset for me in the dropbox? Thank you :D

**Comment by dreavjr** [comment]
Hi! Thank you for your feedback and your interest. We do not detain the rights for the PH2 dataset. It belongs to the University of Porto. You may find the download instructions here: https://www.fc.up.pt/addi/ph2%20database.html
